# Generated by Django 3.2 on 2026-08-29 15:28

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='ProductIdea',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=200, unique=True, verbose_name='Nombre del producto')),
                ('slug', models.SlugField(blank=True, max_length=220, unique=True)),
                ('category', models.CharField(blank=True, max_length=120, verbose_name='Categoria')),
                ('alibaba_url', models.URLField(blank=True, verbose_name='URL en Alibaba')),
                ('supplier_name', models.CharField(blank=True, max_length=200, verbose_name='Proveedor')),
                ('supplier_verified', models.BooleanField(default=False, verbose_name='Proveedor verificado')),
                ('trade_assurance', models.BooleanField(default=False, verbose_name='Con Trade Assurance')),
                ('moq', models.PositiveIntegerField(default=0, verbose_name='MOQ (pedido minimo)')),
                ('status', models.CharField(choices=[('researching', 'Investigando'), ('samples', 'Muestras pedidas'), ('ordered', 'Pedido realizado'), ('selling', 'En venta'), ('discarded', 'Descartado')], default='researching', max_length=20, verbose_name='Estado')),
                ('notes', models.TextField(blank=True, verbose_name='Notas de investigacion')),
                ('demand', models.FloatField(default=5, help_text='Volumen de busquedas/ventas estimado. 10 = altisima demanda.', validators=[django.core.validators.MinValueValidator(0), django.core.validators.MaxValueValidator(10)], verbose_name='Demanda (0-10)')),
                ('competition', models.FloatField(default=5, help_text='10 = mercado saturado, 0 = sin competencia.', validators=[django.core.validators.MinValueValidator(0), django.core.validators.MaxValueValidator(10)], verbose_name='Competencia (0-10)')),
                ('trend', models.FloatField(default=5, help_text='Google Trends 12-24 meses. 10 = crecimiento sostenido.', validators=[django.core.validators.MinValueValidator(0), django.core.validators.MaxValueValidator(10)], verbose_name='Tendencia (0-10)')),
                ('seasonality', models.FloatField(default=5, help_text='10 = solo se vende en una epoca del anyo.', validators=[django.core.validators.MinValueValidator(0), django.core.validators.MaxValueValidator(10)], verbose_name='Estacionalidad (0-10)')),
                ('logistics_difficulty', models.FloatField(default=5, help_text='Peso, volumen, fragilidad, baterias... 10 = pesadilla.', validators=[django.core.validators.MinValueValidator(0), django.core.validators.MaxValueValidator(10)], verbose_name='Dificultad logistica (0-10)')),
                ('regulatory_risk', models.FloatField(default=5, help_text='Certificaciones CE, patentes, marcas. 10 = riesgo alto.', validators=[django.core.validators.MinValueValidator(0), django.core.validators.MaxValueValidator(10)], verbose_name='Riesgo regulatorio (0-10)')),
                ('units', models.PositiveIntegerField(default=100, verbose_name='Unidades del pedido')),
                ('fob_unit_price', models.FloatField(default=0, verbose_name='Precio FOB por unidad (EUR)')),
                ('sample_cost', models.FloatField(default=0, verbose_name='Muestras/moldes/branding (EUR)')),
                ('freight_total', models.FloatField(default=0, verbose_name='Flete internacional (EUR)')),
                ('insurance_total', models.FloatField(default=0, verbose_name='Seguro (EUR)')),
                ('duty_pct', models.FloatField(default=0, verbose_name='Arancel % (sobre CIF)')),
                ('import_vat_pct', models.FloatField(default=21, verbose_name='IVA importacion %')),
                ('customs_fees', models.FloatField(default=0, verbose_name='Despacho de aduanas (EUR)')),
                ('inland_transport', models.FloatField(default=0, verbose_name='Transporte nacional (EUR)')),
                ('vat_recoverable', models.BooleanField(default=True, help_text='Marcar si eres empresa/autonomo y deduces el IVA soportado.', verbose_name='IVA de importacion recuperable')),
                ('sale_price', models.FloatField(default=0, verbose_name='PVP con IVA (EUR)')),
                ('sale_vat_pct', models.FloatField(default=21, verbose_name='IVA de venta %')),
                ('marketplace_fee_pct', models.FloatField(default=0, help_text='Amazon ~15%, tienda propia 0%.', verbose_name='Comision plataforma %')),
                ('payment_fee_pct', models.FloatField(default=0, verbose_name='Comision de pago %')),
                ('fulfillment_per_unit', models.FloatField(default=0, verbose_name='Envio al cliente por unidad (EUR)')),
                ('packaging_per_unit', models.FloatField(default=0, verbose_name='Embalaje por unidad (EUR)')),
                ('marketing_per_unit', models.FloatField(default=0, verbose_name='Publicidad por unidad vendida (EUR)')),
                ('returns_pct', models.FloatField(default=0, verbose_name='Devoluciones %')),
                ('monthly_fixed_costs', models.FloatField(default=0, verbose_name='Costes fijos mensuales (EUR)')),
                ('estimated_monthly_sales', models.PositiveIntegerField(default=0, verbose_name='Ventas mensuales estimadas (uds)')),
                ('opportunity_score', models.FloatField(default=0, editable=False, verbose_name='Puntuacion de oportunidad')),
                ('landed_cost_per_unit', models.FloatField(default=0, editable=False, verbose_name='Coste aterrizado/ud')),
                ('profit_per_unit', models.FloatField(default=0, editable=False, verbose_name='Beneficio/ud')),
                ('net_margin_pct', models.FloatField(default=0, editable=False, verbose_name='Margen neto %')),
                ('roi_pct', models.FloatField(default=0, editable=False, verbose_name='ROI del pedido %')),
                ('created', models.DateTimeField(auto_now_add=True)),
                ('updated', models.DateTimeField(auto_now=True)),
            ],
            options={
                'verbose_name': 'Idea de producto',
                'verbose_name_plural': 'Ideas de producto',
                'ordering': ['-opportunity_score'],
            },
        ),
    ]
