# Generated by Django 5.1.3 on 2024-11-30 16:08

import django.core.validators
import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='IphoneCase',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=256, null=True, unique=True, verbose_name='Title')),
                ('number_copies_stock', models.PositiveSmallIntegerField(default=0, help_text='Stock between 0 and 10', validators=[django.core.validators.MaxValueValidator(30)], verbose_name='Stock')),
                ('path_to_cover_image', models.ImageField(help_text='Select the poster of the case', upload_to='', verbose_name='Poster image')),
                ('price', models.DecimalField(decimal_places=2, help_text='Price cant be negative', max_digits=7, validators=[django.core.validators.MinValueValidator(0)], verbose_name='Price')),
                ('slug', models.SlugField(blank=True, null=True, unique=True, verbose_name='Url slug')),
                ('description', models.CharField(blank=True, default='Description no available', help_text='Sort description of the case', max_length=1024, null=True, verbose_name='Description')),
                ('score', models.PositiveSmallIntegerField(default=0, help_text='Score between 0 and 10', validators=[django.core.validators.MaxValueValidator(10)], verbose_name='Score')),
            ],
            options={
                'verbose_name': 'Case',
                'verbose_name_plural': 'Cases',
                'ordering': ['name', 'number_copies_stock', 'price'],
            },
        ),
        migrations.CreateModel(
            name='Comment',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('date_time', models.DateTimeField(auto_now_add=True, verbose_name='Comment date')),
                ('msg', models.TextField(max_length=512, verbose_name='Message')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL, verbose_name='Usuario')),
                ('case', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='catalog.iphonecase', verbose_name='Case')),
            ],
            options={
                'verbose_name': 'Comment',
                'verbose_name_plural': 'Comments',
                'ordering': ['date_time', 'msg', 'user', 'case'],
            },
        ),
    ]
