# Generated by Django 5.1.3 on 2025-01-07 02:59

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('catalog', '0002_iphonecase_color_iphonecase_model_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='iphonecase',
            name='model',
            field=models.CharField(max_length=256, null=True, verbose_name='Model'),
        ),
    ]
