# Generated by Django 5.1.3 on 2024-12-02 15:46

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('orders', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='TransaccionPaypal',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('payer_id', models.CharField(max_length=256)),
                ('payment_date', models.DateTimeField()),
                ('payment_status', models.CharField(max_length=256)),
                ('quantity', models.IntegerField()),
                ('invoce', models.CharField(max_length=256)),
                ('first_name', models.CharField(max_length=256)),
                ('payer_status', models.CharField(max_length=256)),
                ('payer_email', models.CharField(max_length=256)),
                ('txn_id', models.CharField(max_length=256)),
                ('receiver_id', models.CharField(max_length=256)),
                ('payment_gross', models.FloatField()),
                ('custom', models.CharField(max_length=256)),
            ],
        ),
    ]
